# /=============================================================================\
# | vibe coded powershell script for automatically patching 32bit games with    |
# | patchlaa, 4gb Patch, or Microsoft's editbin.                                |
# |_____________________________________________________________________________|
# | automatically finds Steam, GOG and Epic libraries on the PC, asks for other |
# | folders to include, and skips non-game files.                               |
# |_____________________________________________________________________________|
# | prompted by idontknowshark, generated by deepseek.                          |
# |_____________________________________________________________________________|
# | visit bordiga.party if you like bordiga                                     |
# | visit https://rateyourmusic.com/~idontknowshark if you like black metal     |
# |_____________________________________________________________________________|
# | thanks for using the script!                                                |
# \=============================================================================/


# Self-elevate to administrator (required for patching)
if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Host "This script requires administrator privileges. Restarting with elevation..." -ForegroundColor Yellow
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}

# --- Helper Functions ---
function Write-VerboseMsg {
    param([string]$Message, [string]$Color = "White")
    $timestamp = Get-Date -Format "HH:mm:ss.fff"
    Write-Host "[$timestamp] $Message" -ForegroundColor $Color
}

function Remove-Quotes {
    param([string]$Path)
    if ($Path -match '^"(.+)"$') { return $matches[1] }
    return $Path
}

function Install-patchlaa {
    Write-VerboseMsg "Installing patchlaa via Cargo..." -Color Yellow
    try {
        # Check if cargo command exists
        $cargoExists = Get-Command cargo -ErrorAction SilentlyContinue
        if (-not $cargoExists) {
            Write-VerboseMsg "Cargo (Rust) not found. Do you want to install Rust now?" -Color Cyan
            $installRust = Read-Host "Enter y/n (default: y)"
            if ($installRust -ne 'n') {
                # Try winget first
                $wingetExists = Get-Command winget -ErrorAction SilentlyContinue
                if ($wingetExists) {
                    Write-VerboseMsg "Installing Rust via winget..." -Color Yellow
                    winget install --id=Rustlang.Rustup -e --accept-source-agreements --accept-package-agreements
                    if ($LASTEXITCODE -ne 0) { throw "winget installation failed" }
                } else {
                    # Fallback to direct download
                    Write-VerboseMsg "winget not found. Downloading Rust installer..." -Color Yellow
                    $installerPath = "$env:TEMP\rustup-init.exe"
                    # Ensure TLS 1.2 for older Windows
                    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                    Invoke-WebRequest -Uri "https://win.rustup.rs/x86_64" -OutFile $installerPath
                    Write-VerboseMsg "Running Rust installer (default options)..." -Color Yellow
                    Start-Process -FilePath $installerPath -ArgumentList "-y" -Wait -NoNewWindow
                    Remove-Item $installerPath -Force -ErrorAction SilentlyContinue
                }
                
                # Refresh PATH and wait a moment for system to register changes
                Write-VerboseMsg "Refreshing environment variables..." -Color Gray
                $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
                
                # Sometimes PATH takes a moment – retry up to 3 times with delay
                $cargoExists = $null
                for ($i = 1; $i -le 3; $i++) {
                    Start-Sleep -Seconds 2
                    $cargoExists = Get-Command cargo -ErrorAction SilentlyContinue
                    if ($cargoExists) { break }
                }
                
                if (-not $cargoExists) {
                    # Manual check in common Cargo bin paths
                    $cargoPaths = @(
                        "$env:USERPROFILE\.cargo\bin\cargo.exe",
                        "$env:ProgramFiles\Rust stable GNU\bin\cargo.exe",
                        "${env:ProgramFiles(x86)}\Rust stable GNU\bin\cargo.exe"
                    )
                    foreach ($cp in $cargoPaths) {
                        if (Test-Path $cp) {
                            Write-VerboseMsg "Found cargo manually at: $cp" -Color Green
                            $cargoDir = Split-Path $cp -Parent
                            $env:Path = "$cargoDir;$env:Path"
                            $cargoExists = Get-Command cargo -ErrorAction SilentlyContinue
                            break
                        }
                    }
                }
                
                if (-not $cargoExists) {
                    Write-VerboseMsg "Cargo still not found after installation. Please restart PowerShell and run this script again." -Color Red
                    return $false
                }
            } else {
                Write-VerboseMsg "patchlaa installation cancelled." -Color Red
                return $false
            }
        }
        
        Write-VerboseMsg "Cargo found. Installing patchlaa..." -Color Green
        cargo install patchlaa
        if ($LASTEXITCODE -ne 0) { throw "Cargo install failed with exit code $LASTEXITCODE" }
        Write-VerboseMsg "patchlaa installed successfully." -Color Green
        
        # Refresh PATH again to include the new patchlaa.exe
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        return $true
    } catch {
        Write-VerboseMsg "Failed to install patchlaa: $_" -Color Red
        return $false
    }
}

function Ensure-Patcher {
    param([string]$Choice)
    
    if ($Choice -eq "1") {
        # patchlaa
        $existing = (Get-Command patchlaa.exe -ErrorAction SilentlyContinue).Source
        if ($existing) {
            Write-VerboseMsg "patchlaa found at: $existing" -Color Green
            return @{Path = $existing; Name = "patchlaa"}
        }
        Write-VerboseMsg "patchlaa not found. Attempting to install..." -Color Cyan
        if (Install-patchlaa) {
            $newPath = (Get-Command patchlaa.exe -ErrorAction SilentlyContinue).Source
            if ($newPath) {
                Write-VerboseMsg "patchlaa installed successfully." -Color Green
                return @{Path = $newPath; Name = "patchlaa"}
            } else {
                Write-VerboseMsg "patchlaa installed but not found in PATH. Please restart PowerShell and re‑run the script." -Color Red
                return $null
            }
        }
        return $null
    }
    elseif ($Choice -eq "2") {
        # 4GB Patch
        $existing = (Get-Command 4gb_patch.exe -ErrorAction SilentlyContinue).Source
        if (-not $existing) {
            $commonPaths = @(
                "${env:ProgramFiles}\NTCore\4GB Patch\4gb_patch.exe",
                "${env:ProgramFiles(x86)}\NTCore\4GB Patch\4gb_patch.exe",
                "$env:USERPROFILE\Downloads\4gb_patch.exe"
            )
            foreach ($path in $commonPaths) {
                if (Test-Path $path) { $existing = $path; break }
            }
        }
        if ($existing) {
            Write-VerboseMsg "4GB Patch found at: $existing" -Color Green
            return @{Path = $existing; Name = "4gb_patch"}
        }
        Write-VerboseMsg "`n4GB Patch not found automatically." -Color Yellow
        Write-VerboseMsg "Please enter the full path to 4gb_patch.exe (e.g., C:\Tools\4gb_patch.exe)" -Color White
        Write-VerboseMsg "If you don't have it, you can download it from: https://ntcore.com/4gb-patch/" -Color Gray
        $userPath = Read-Host "Path"
        $userPath = Remove-Quotes $userPath
        if ((Test-Path $userPath) -and ($userPath -like "*.exe")) {
            Write-VerboseMsg "Using 4GB Patch at: $userPath" -Color Green
            return @{Path = $userPath; Name = "4gb_patch"}
        } else {
            Write-VerboseMsg "Invalid path or file not found. Exiting." -Color Red
            return $null
        }
    }
    elseif ($Choice -eq "3") {
        # Microsoft editbin
        Write-VerboseMsg "Searching for Microsoft editbin.exe..." -Color Yellow
        $editbinPaths = @(
            "${env:ProgramFiles}\Microsoft Visual Studio\2022\*\VC\Tools\MSVC\*\bin\Hostx64\x64\editbin.exe",
            "${env:ProgramFiles}\Microsoft Visual Studio\2022\*\VC\Tools\MSVC\*\bin\Hostx86\x86\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\*\VC\Tools\MSVC\*\bin\Hostx64\x64\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\*\VC\Tools\MSVC\*\bin\Hostx86\x86\editbin.exe",
            "${env:ProgramFiles}\Microsoft Visual Studio\2019\*\VC\Tools\MSVC\*\bin\Hostx64\x64\editbin.exe",
            "${env:ProgramFiles}\Microsoft Visual Studio\2019\*\VC\Tools\MSVC\*\bin\Hostx86\x86\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\*\VC\Tools\MSVC\*\bin\Hostx64\x64\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\*\VC\Tools\MSVC\*\bin\Hostx86\x86\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\*\VC\Tools\MSVC\*\bin\Hostx64\x64\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\*\VC\Tools\MSVC\*\bin\Hostx86\x86\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio 10.0\VC\bin\editbin.exe",
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio 10.0\VC\bin\amd64\editbin.exe",
            (Get-Command editbin.exe -ErrorAction SilentlyContinue).Source
        )
        $existing = $null
        foreach ($pathPattern in $editbinPaths) {
            $resolvedPaths = Resolve-Path $pathPattern -ErrorAction SilentlyContinue
            foreach ($resolvedPath in $resolvedPaths) {
                if (Test-Path $resolvedPath) { $existing = $resolvedPath.Path; break }
            }
            if ($existing) { break }
        }
        if ($existing) {
            Write-VerboseMsg "Microsoft editbin found at: $existing" -Color Green
            $editbinDir = Split-Path $existing -Parent
            Write-VerboseMsg "Note: editbin may require VC runtime DLLs. Working directory will be set to $editbinDir" -Color DarkGray
            return @{Path = $existing; Name = "editbin"; Arguments = "/LARGEADDRESSAWARE /NOLOGO"; WorkingDirectory = $editbinDir}
        } else {
            Write-VerboseMsg "`nMicrosoft editbin.exe not found." -Color Red
            Write-VerboseMsg "This tool is part of Visual Studio Build Tools or Visual Studio." -Color Yellow
            Write-VerboseMsg "You can install the free Visual Studio Community or Build Tools from:" -Color Yellow
            Write-VerboseMsg "https://visualstudio.microsoft.com/downloads/" -Color Cyan
            Write-VerboseMsg "Make sure to select the 'C++ build tools' workload during installation." -Color Yellow
            Write-VerboseMsg "Alternatively, you can manually provide the full path." -Color Gray
            $userPath = Read-Host "Enter full path to editbin.exe (or press Enter to cancel)"
            if ($userPath) {
                $userPath = Remove-Quotes $userPath
                if (Test-Path $userPath) {
                    Write-VerboseMsg "Using editbin at: $userPath" -Color Green
                    $editbinDir = Split-Path $userPath -Parent
                    return @{Path = $userPath; Name = "editbin"; Arguments = "/LARGEADDRESSAWARE /NOLOGO"; WorkingDirectory = $editbinDir}
                } else {
                    Write-VerboseMsg "File not found. Exiting." -Color Red
                    return $null
                }
            } else {
                Write-VerboseMsg "editbin selection cancelled. Exiting." -Color Red
                return $null
            }
        }
    }
    else {
        Write-VerboseMsg "Invalid patcher choice. Exiting." -Color Red
        return $null
    }
}

# --- Main Script ---
Write-VerboseMsg "=== Powershell LAA Autopatcher ===" -Color Cyan

# --- Patcher Selection ---
Write-VerboseMsg "`nWhich patching tool would you like to use?" -Color Yellow
Write-VerboseMsg "  1) patchlaa     – Lightweight. Requires Rust. (98% success rate; recommended)" -Color Green
Write-VerboseMsg "  2) 4GB Patch    – No dependencies. (deprecated; CLI unreliable)" -Color Red
Write-VerboseMsg "  3) editbin      – Microsoft tool. Requires VSBT (100% success rate; slow; large download)" -Color Yellow
$patcherChoice = Read-Host "Enter 1, 2, or 3 (default: 1)"

if ($patcherChoice -eq "2") { 
    Write-VerboseMsg "`n⚠ WARNING: The 4GB Patch command-line mode is unreliable." -Color Red
    Write-VerboseMsg "This script was designed with patchlaa as the primary patcher." -Color Yellow
    Write-VerboseMsg "4GB Patch may not parse paths correctly and could spam file dialogs." -Color Yellow
    Write-VerboseMsg "Continuing with 4GB Patch...`n" -Color Gray
} elseif ($patcherChoice -eq "3") {
    Write-VerboseMsg "`nℹ INFO: editbin requires Visual Studio Build Tools." -Color Cyan
    Write-VerboseMsg "The script will attempt to locate it automatically." -Color Cyan
    Write-VerboseMsg "If not found, you will be prompted to provide the path manually.`n" -Color Cyan
} else {
    $patcherChoice = "1"
}

# Ask about backups (only relevant for patchers that don't create them)
Write-VerboseMsg "`nDo you want to create backups (.exe.backup) before patching?" -Color Cyan
$createBackups = Read-Host "Enter y/n (default: n)"
if ($createBackups -eq 'y') {
    Write-VerboseMsg "Backups will be created for each patched executable." -Color Green
} else {
    Write-VerboseMsg "No backups will be created." -Color Gray
}

$patcher = Ensure-Patcher -Choice $patcherChoice
if (-not $patcher) {
    Write-VerboseMsg "Failed to obtain a patcher. Exiting." -Color Red
    Read-Host "Press Enter to exit"
    exit 1
}
Write-VerboseMsg "Using patcher: $($patcher.Name) at $($patcher.Path)" -Color Cyan

$gameFolders = @()

# --- Auto-detect game libraries ---
Write-VerboseMsg "`nStep 2: Auto-detecting game libraries..." -Color Yellow

# Steam
Write-VerboseMsg "  [Scanning] Steam libraries..." -Color Gray
$steamFolders = @()
$regPath = "HKLM:\SOFTWARE\WOW6432Node\Valve\Steam"
$steamInstallPath = $null
try {
    $steamInstallPath = (Get-ItemProperty -Path $regPath -ErrorAction Stop).InstallPath
    if ($steamInstallPath) {
        $steamCommon = Join-Path $steamInstallPath "steamapps\common"
        if (Test-Path $steamCommon) { $steamFolders += $steamCommon }
    }
} catch { Write-VerboseMsg "    Steam not found in registry." -Color DarkYellow }

if ($steamInstallPath) {
    $vdfPath = Join-Path $steamInstallPath "steamapps\libraryfolders.vdf"
    if (Test-Path $vdfPath) {
        $vdfContent = Get-Content $vdfPath -Raw
        $matches = [regex]::Matches($vdfContent, '\\"path\\":\\"([^\\"]+)\\"')
        foreach ($match in $matches) {
            $commonPath = Join-Path $match.Groups[1].Value "steamapps\common"
            if (Test-Path $commonPath) { $steamFolders += $commonPath }
        }
    }
}
$steamFolders = $steamFolders | Select-Object -Unique
if ($steamFolders.Count -gt 0) {
    Write-VerboseMsg "`n  Steam libraries found:" -Color Cyan
    $steamFolders | ForEach-Object { Write-VerboseMsg "    - $_" -Color Gray }
    $includeSteam = Read-Host "  Include Steam folders in patching? (y/n, default: y)"
    if ($includeSteam -ne 'n') {
        $gameFolders += $steamFolders
        Write-VerboseMsg "  Steam folders added." -Color Green
    } else {
        Write-VerboseMsg "  Steam folders skipped." -Color DarkGray
    }
} else {
    Write-VerboseMsg "    No Steam libraries found." -Color DarkGray
}

# GOG
Write-VerboseMsg "`n  [Scanning] GOG libraries..." -Color Gray
$gogFolders = @()
$gogDefault = "C:\Program Files (x86)\GOG Galaxy\Games"
if (Test-Path $gogDefault) { $gogFolders += $gogDefault }
$gogRegPath = "HKLM:\SOFTWARE\WOW6432Node\GOG.com\Games"
if (Test-Path $gogRegPath) {
    $gogKeys = Get-ChildItem -Path $gogRegPath -ErrorAction SilentlyContinue
    foreach ($key in $gogKeys) {
        $gamePath = (Get-ItemProperty -Path $key.PSPath -ErrorAction SilentlyContinue).path
        if ($gamePath -and (Test-Path $gamePath)) { $gogFolders += $gamePath }
    }
}
$gogFolders = $gogFolders | Select-Object -Unique
if ($gogFolders.Count -gt 0) {
    Write-VerboseMsg "`n  GOG libraries found:" -Color Cyan
    $gogFolders | ForEach-Object { Write-VerboseMsg "    - $_" -Color Gray }
    $includeGOG = Read-Host "  Include GOG folders in patching? (y/n, default: n)"
    if ($includeGOG -eq 'y') {
        $gameFolders += $gogFolders
        Write-VerboseMsg "  GOG folders added." -Color Green
    } else {
        Write-VerboseMsg "  GOG folders skipped." -Color DarkGray
    }
} else {
    Write-VerboseMsg "    No GOG libraries found." -Color DarkGray
}

# Epic
Write-VerboseMsg "`n  [Scanning] Epic libraries..." -Color Gray
$epicFolders = @()
$epicDefault = "C:\Program Files\Epic Games"
if (Test-Path $epicDefault) { $epicFolders += $epicDefault }
$manifestPath = "$env:ProgramData\Epic\EpicGamesLauncher\Data\Manifests"
if (Test-Path $manifestPath) {
    $manifestFiles = Get-ChildItem -Path $manifestPath -Filter "*.item" -ErrorAction SilentlyContinue
    foreach ($file in $manifestFiles) {
        try {
            $manifestContent = Get-Content $file.FullName -Raw -ErrorAction Stop
            if ($manifestContent -match '"InstallLocation":\s*"([^"]+)"') {
                $installPath = $matches[1]
                if (Test-Path $installPath) { $epicFolders += $installPath }
            }
        } catch { }
    }
}
$epicFolders = $epicFolders | Select-Object -Unique
if ($epicFolders.Count -gt 0) {
    Write-VerboseMsg "`n  Epic libraries found:" -Color Cyan
    $epicFolders | ForEach-Object { Write-VerboseMsg "    - $_" -Color Gray }
    $includeEpic = Read-Host "  Include Epic folders in patching? (y/n, default: n)"
    if ($includeEpic -eq 'y') {
        $gameFolders += $epicFolders
        Write-VerboseMsg "  Epic folders added." -Color Green
    } else {
        Write-VerboseMsg "  Epic folders skipped." -Color DarkGray
    }
} else {
    Write-VerboseMsg "    No Epic libraries found." -Color DarkGray
}

# Additional custom folders
Write-VerboseMsg "`nDo you want to add any additional game folders (e.g., custom installations or other launchers)?" -Color Cyan
$addMore = Read-Host "Enter y/n (default: n)"
if ($addMore -eq 'y') {
    Write-VerboseMsg "Enter full folder paths (one per line). Type 'done' when finished:" -Color Yellow
    while ($true) {
        $path = Read-Host "Path"
        if ($path -eq 'done') { break }
        $path = Remove-Quotes $path
        if (Test-Path $path) {
            $gameFolders += $path
            Write-VerboseMsg "  Added: $path" -Color Green
        } else {
            Write-VerboseMsg "  Path not found: $path" -Color Red
        }
    }
}

# User-defined ignore patterns
$userPatterns = @()
Write-VerboseMsg "`nDo you want to specify folders or .exe names to skip?" -Color Cyan
$skipConfig = Read-Host "Enter y/n (default: n)"
if ($skipConfig -eq 'y') {
    Write-VerboseMsg "Enter patterns to ignore (e.g., 'Mods', 'Launcher.exe', 'bin'). One per line. Type 'done' when finished:" -Color Yellow
    while ($true) {
        $pattern = Read-Host "Ignore"
        if ($pattern -eq 'done') { break }
        if ($pattern -ne '') {
            $userPatterns += $pattern
            Write-VerboseMsg "  Will skip: $pattern" -Color DarkGray
        }
    }
}

$defaultExcludes = @(
    "_CommonRedist", "DotNet", "DirectX", "VCRedist", "EasyAntiCheat", "BattlEye",
    "AntiCheat", "steamapps\common\Steamworks Shared", "__Installer", "Support",
    "Redist", "Tools", "*backup*",
    "*unins*.exe", "*uninstall*.exe", "*Uninstall*.exe", "*remove*.exe", "*cleanup*.exe",
    "*setup*.exe", "*install*.exe", "*Installer*.exe", "*redist*.exe",
    "*dxsetup*.exe", "*dxwebsetup*.exe", "*vcredist*.exe", "*dotnet*.exe",
    "*oalinst*.exe", "*UE4PrereqSetup*.exe", "*EpicOnlineServicesInstaller*.exe",
    "*patcher*.exe", "*patch*.exe", "*updater*.exe", "*helper*.exe", "*service*.exe",
    "*crash*.exe", "*error*.exe", "*report*.exe", "*dump*.exe", "*bugsplat*.exe",
    "*UnityCrashHandler*.exe", "*BsSndRpt*.exe", "*BugSplat*.exe",
    "cgc.exe", "nvdxt.exe", "fxc.exe", "texconv.exe", "texassemble.exe",
    "QuickSFV.exe", "elevate.exe", "ffmpeg.exe", "webclient.exe", "winlive-webclient.exe"
)
$ignorePatterns = $defaultExcludes + $userPatterns

if ($gameFolders.Count -eq 0) {
    Write-VerboseMsg "No game folders selected! Exiting." -Color Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-VerboseMsg "`nTotal game folders to scan: $($gameFolders.Count)" -Color Cyan
$gameFolders | ForEach-Object { Write-VerboseMsg " - $_" -Color Gray }
Write-VerboseMsg "`nStep 3: Starting automatic LAA patching process..." -Color Cyan

# --- Scan and patch ---
$totalPatched = 0
$skippedList = @()
$failedList = @()
$backupCreatedCount = 0
$totalExeFilesFound = 0
$total32BitExeFiles = 0

foreach ($libraryPath in $gameFolders) {
    Write-VerboseMsg "`n=== Scanning: $libraryPath ===" -Color Yellow
    $allExes = Get-ChildItem -Path $libraryPath -Filter "*.exe" -Recurse -ErrorAction SilentlyContinue
    Write-VerboseMsg "Found $($allExes.Count) .exe files in this folder (including subfolders)." -Color Gray

    foreach ($exeFile in $allExes) {
        $exePath = $exeFile.FullName
        $totalExeFilesFound++
        Write-VerboseMsg "`n  [$totalExeFilesFound] Processing: $($exeFile.Name)" -Color White
        Write-VerboseMsg "    Full path: $exePath" -Color DarkGray

        # Check ignore patterns
        $shouldSkip = $false
        foreach ($pattern in $ignorePatterns) {
            if ($exePath -like "*$pattern*" -or $exeFile.Name -like $pattern) {
                $shouldSkip = $true
                Write-VerboseMsg "    ⚠ SKIPPED by pattern: $pattern" -Color DarkGray
                break
            }
        }
        if ($shouldSkip) {
            $skippedList += $exePath
            continue
        }

        # Architecture check
        Write-VerboseMsg "    Checking PE header architecture..." -Color Gray
        try {
            $peHeader = Get-Content $exePath -Encoding Byte -TotalCount 4096 -ErrorAction Stop
            $offset = [BitConverter]::ToInt32($peHeader, 0x3C) + 4
            $machine = [BitConverter]::ToUInt16($peHeader, $offset)
            Write-VerboseMsg "    Machine type code: 0x$($machine.ToString('X'))" -Color Gray
            if ($machine -eq 0x14C) {
                Write-VerboseMsg "    ✓ Architecture: 32-bit (eligible for LAA)" -Color Green
                $total32BitExeFiles++
            } elseif ($machine -eq 0x8664) {
                Write-VerboseMsg "    ✗ Architecture: 64-bit (LAA not needed/not applicable)" -Color DarkYellow
                $skippedList += $exePath
                continue
            } else {
                Write-VerboseMsg "    ? Unknown machine type: 0x$($machine.ToString('X')) - skipping" -Color DarkYellow
                $skippedList += $exePath
                continue
            }
        } catch {
            Write-VerboseMsg "    ⚠ WARNING: Could not read PE header: $_" -Color DarkRed
            Write-VerboseMsg "    Skipping this file to be safe." -Color DarkRed
            $skippedList += $exePath
            continue
        }

        # --- Create backup if requested ---
        if ($createBackups -eq 'y') {
            $backupPath = "$exePath.backup"
            if (Test-Path $backupPath) {
                Write-VerboseMsg "    ⚠ Backup already exists: $backupPath (skipping)" -Color DarkGray
            } else {
                try {
                    Copy-Item -Path $exePath -Destination $backupPath -Force
                    Write-VerboseMsg "    📁 Backup created: $backupPath" -Color Cyan
                    $backupCreatedCount++
                } catch {
                    Write-VerboseMsg "    ❌ Failed to create backup: $_" -Color Red
                    # Continue anyway – patching might still work
                }
            }
        }

        # Apply patch
        Write-VerboseMsg "    🛠 Attempting to patch: $($exeFile.Name)" -Color Cyan
        try {
            switch ($patcher.Name) {
                "patchlaa" {
                    $cmd = "& `"$($patcher.Path)`" `"$exePath`""
                    Write-VerboseMsg "    Command: $cmd" -Color Gray
                    $output = & $patcher.Path $exePath 2>&1
                    $exitCode = $LASTEXITCODE
                }
                "4gb_patch" {
                    $cmd = "& `"$($patcher.Path)`" `"$exePath`""
                    Write-VerboseMsg "    Command: $cmd" -Color Gray
                    $process = Start-Process -FilePath $patcher.Path -ArgumentList "`"$exePath`"" -NoNewWindow -Wait -PassThru
                    $exitCode = $process.ExitCode
                    $output = $null
                }
                "editbin" {
                    $arguments = "$($patcher.Arguments) `"$exePath`""
                    Write-VerboseMsg "    Command: & `"$($patcher.Path)`" $arguments" -Color Gray
                    Write-VerboseMsg "    Working directory set to: $($patcher.WorkingDirectory)" -Color DarkGray
                    $process = Start-Process -FilePath $patcher.Path -ArgumentList $arguments -NoNewWindow -Wait -PassThru -WorkingDirectory $patcher.WorkingDirectory
                    $exitCode = $process.ExitCode
                    $output = $null
                }
                default { throw "Unknown patcher type: $($patcher.Name)" }
            }

            Write-VerboseMsg "    Patcher output:" -Color Gray
            if ($output) { $output | ForEach-Object { Write-VerboseMsg "      $_" -Color Gray } }
            else { Write-VerboseMsg "      (no output)" -Color Gray }

            if ($exitCode -eq 0) {
                $totalPatched++
                Write-VerboseMsg "    ✅ SUCCESS: $($exeFile.Name) is now Large Address Aware!" -Color Green
            } else {
                throw "Patcher exited with code $exitCode"
            }
        } catch {
            Write-VerboseMsg "    ❌ FAILED: $_" -Color Red
            $failedList += $exePath
        }
    }
}

# Summary
Write-VerboseMsg "`n=== PATCHING COMPLETE ===" -Color Cyan
Write-VerboseMsg "Total .exe files scanned: $totalExeFilesFound" -Color White
Write-VerboseMsg "  - 32-bit executables found: $total32BitExeFiles" -Color Gray
Write-VerboseMsg "  - Successfully patched: $totalPatched" -Color Green
Write-VerboseMsg "  - Skipped (by rules or architecture): $($skippedList.Count)" -Color DarkYellow
Write-VerboseMsg "  - Failed to patch: $($failedList.Count)" -Color $(if ($failedList.Count -gt 0) { "Red" } else { "Green" })
if ($createBackups -eq 'y') {
    Write-VerboseMsg "  - Backups created: $backupCreatedCount" -Color Cyan
}

if ($failedList.Count -gt 0) {
    Write-VerboseMsg "`n--- Failed Executables ---" -Color Red
    $failedList | ForEach-Object { Write-VerboseMsg "  - $_" -Color Red }
}

if ($skippedList.Count -gt 0 -and $skippedList.Count -le 20) {
    Write-VerboseMsg "`n--- Skipped Executables (first 20 shown) ---" -Color DarkYellow
    $skippedList | Select-Object -First 20 | ForEach-Object { Write-VerboseMsg "  - $_" -Color DarkGray }
} elseif ($skippedList.Count -gt 20) {
    Write-VerboseMsg "`n--- $($skippedList.Count) executables were skipped. ---" -Color DarkYellow
}

Write-VerboseMsg "`nScript finished." -Color Cyan
Read-Host "Press Enter to exit"
